### ISSUE TITLE
Which DHT Library?

### ISSUE THREAD

**Issue by jpaustin** [fowlerk/ESP8266-Color-Weather-Station-v8#5]
I attempted to compile with the Adafruit DHT library thinking that was the defacto standard DHT library but I get a compile error. To get around the error I have had to comment out all DHT lines. Is there a preferred DHT library? Yes I understand you have it set to FALSE as far as testing for the presence of the sensor but I believe you still need to have the library present to compile. 

Correct me if I am wrong...

**Comment by fowlerk** [comment]
Yes, the DHT library I have installed is the Adafruit one, specifically v1.3.0 (which I assume to be the latest based on the IDE library manager).  And yes, I overlooked documenting this in the most recent addition to the README since I don't use it.  It is however, currently required for compilation unless you comment out all the references.

What compile errors did you get with the Adafruit library?  Were you using the latest IDE/DHT lib?

**Comment by fowlerk** [comment]
Ahh, it appears that the DHT library also requires the Adafruit Unified Sensor library which it references.  I happen to also have this installed (v1.0.2).  Perhaps that is the source of your issue.  I'm adding both to the README library requirements for future reference.

**Comment by fowlerk** [comment]
Added both to the README for the library requirements...

**Comment by jpaustin** [comment]
Yes that was the issue and thanks for following up and closing it out. Awesome project BTW. Appreciate all the hard work you put into it as well as Squix original code.

**Comment by fowlerk** [comment]
Thanks for the feedback...I'm glad others find it useful.  Not sure if you're running v8 or v9, but I really like the weather alert enhancements added in v9.  I have also been adding some substantial icon improvements in the latest version, but still doing some debugging.  Hope to get that one up soon.  I've uncovered several icon issues that occur with the existing Weather Underground client that I've corrected.
