### ISSUE TITLE
Graphics?

### ISSUE THREAD

**Issue by jpaustin** [fowlerk/ESP8266-Color-Weather-Station-v8#7]
Did the graphics change recently? I did a format and rest the JSON file to create a new download and now my graphics look odd. The top large graphic for the sunny is split in two. Like it rolls off the screen. Smaller graphcs are all garbled and show up as white/yellow smears.

**Comment by fowlerk** [comment]
I ran into this issue several weeks ago while debugging my most recent code changes and spent the better part of a day trying to figure out what I'd changed to break things.  Turns out I'd forgotten that I'd applied updates to several libraries, and realized one of them was the Adafruit_ILI9341 lib.  Tried reverting back to the previous version and voila!  Things worked again!  Looks like contributors are making changes for the ESP32, and I guessed they had broken something for the ESP8266's ability to correctly display bit maps in the process.  I didn't see any issues mentioned on their git page, but figured they would get to the bottom soon, as I didn't have time to look into it further.  

I did a quick check this morning, and found a closed issue (https://github.com/adafruit/Adafruit_ILI9341/issues/27), so it may have been fixed.  The comments allude to an issue with the weather station code, but I haven't yet found the forum reference they mention.  In the meantime, you should be able to revert back to a previous release of the lib (1.0.2? I think) to fix it temporarily.

**Comment by fowlerk** [comment]
Okay, did a bit more digging and think I found the forum reference mentioned here https://forums.adafruit.com/viewtopic.php?f=53&t=114248&p=571341&hilit=Weather#p571341.  It appears this isn't a "bug" per se, but a change in the approach for the way the screen is updated that broke the old bmp-displaying code in GfxUI.cpp.  The fix is mentioned in the forum, but I've not copied the code yet to test it.  Until I do, you can either revert to the prior version, or take a crack at copying the updated code from the Adafruit example and updating your bmp display routine in GfxUI.cpp.

**Comment by fowlerk** [comment]
I have updated the GfxUi.cpp to support the changes required for the latest Adafruit_ILI9341 library, but haven't tested the changes.  Please try to download the change and compile with the latest library versions and see if this fixes the problem.

**Comment by jpaustin** [comment]
Great to get a response on this. I was pulling my hair out last night trying to figure out where I went south. I also updated the Adafruit library and that is when all my troubles started! I will go back and carefully check your latest changes and make sure i have the appropriate libs. 

I did try to roll back only one level last night and that did not fix it. I may have to go back two or more levels worst case. I will let you know how it goes. Thanks again for the support. Do you need to exit the Arduino IDE completely if you change lib versions or is it OK to just recompile? I didn't exit and perhaps that was adding to my misery last night! ;-)

**Comment by jpaustin** [comment]
I just replaced the GfxUi.cpp file with your latest and made sure the latest Adafruit library was installed and can report the graphics are back to normal! Working very well now. Thanks. I may have to give your v9 a try now.

**Comment by fowlerk** [comment]
Excellent.  Glad that took care of the issue, and thanks for testing and reporting back.  I'll close the issue.

If you get brave and want to try out the latest development version, let me know and I'll post it.  Still a few issues to resolve with it, but it is a significant step up from v9.  But, a little more work to get going as I've changed the approach to retrieving the icons.

**Comment by jpaustin** [comment]
I've got v9 working fairly easily. I don't have any rough weather in my area so couldn't test out the alerts! 

You have a follow on beyond v9? I'm interested if yes.

**Comment by fowlerk** [comment]
Yes, current development version contains many enhancements regarding icons and many bug fixes (and maybe a few new ones ;( ).  I found that the original code from squix had a few issues with ambiguous icons (i.e., have you noticed that the "snow" or "chancesnow" is the same as "sleet"?)  I've taken the opportunity to learn how to modify and add my own icons, so have done some work here.  In the process, to avoid breaking squix's original examples, I've added a new function to avoid the use of his icon translations and use the original icon text returned from the API.  This means I've modified the Weather Underground client lib to add this function, and have a new pull request to squix to add this to the main branch.  In the meantime, I'll create a new repository with the development code and some instructions when I get a chance in the next several days, including the modified WU client lib.  Look for the updates coming soon.

**Comment by fowlerk** [comment]
Okay, well that didn't take as long as I thought.  Here's the new "beta" release in its own repository:  https://github.com/fowlerk/ESP8266-Color-Weather-Station-v11d.  I've included a README to detail the steps you need to take to use this version.  As I mentioned, a little more involved, but pretty straightforward I think.  If you end up running it, I'd appreciate any feedback or issues you find.  I've been running it for awhile and it seems pretty stable.

As a side note, if you want to see how the weather alerts work, you can simply enter a location in the configuration where there are currently outstanding weather alerts.  (I've had to do this for testing purposes.)  If you look at the mainline routine, around lines (532-534), you'll see some lines commented out that override the location and timezone for this specific purpose.
