### ISSUE TITLE
Thingspeak / DHT

### ISSUE THREAD

**Issue by anthonyjclarke** [fowlerk/ESP8266-Color-Weather-Station-v8#8]
Hi, 

Just got your code working, love it... I do however want to get my Thingspeak channel displaying.

Other than the uncomment to define the channel I cant see any code to actually display it.

I was also looking for the code that displays the DHT temperature, again, dont see that in the code?

Am I missing something?

Many thanks

**Comment by fowlerk** [comment]
No, you're not...I never implemented it since I don't use it.  The remnants of the Thingspeak channel  and the DHT code are from squix78's original code that used the .96" OLED display, and I don't think it was ever implemented in his color weather station code, which is the basis for this project.  If you want to tackle it, you'll need to decide where you want to display the data (perhaps as a new bottom  panel might be easiest?).   The update routine for the DHT data is still in there, but no display routine.  You can likely get much of the code for Thingspeak from his original work, but you'll have to write your own display code for the LCD. 

I'm glad you found this useful...FWIW, if you want to try a newer version (that requires a bit more work to get running) take a look at version 11d (https://github.com/fowlerk/ESP8266-Color-Weather-Station-v11d).  It has many enhancements over this version.

**Comment by anthonyjclarke** [comment]
Thanks, I worked this out during the course of the day... and so wrote the code.... didn't realised you had an updated version... tomorrows task is to integrate my Thingspeak code to 11d.
Here's what it looks like.... :)
![img_2685](https://cloud.githubusercontent.com/assets/9491428/26549614/34bc60a0-44bd-11e7-8113-4c391a34772f.jpg)

**Comment by fowlerk** [comment]
That looks great!  I might have to look at adding that to mine...do you have the code up somewhere and do you mind sharing it?

ATM I'm working on some touch-screen additions to 11d...just getting started though and haven't gotten very far.

**Comment by anthonyjclarke** [comment]
I'll tidy it up / document it / and have created a placeholder here - https://github.com/anthonyjclarke/ESP8266-Color-Weather-Station-v8-TS
